"""
Django settings for websitem project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Both of these stay development-friendly by default and are overridden by the
# environment where it matters: a public deployment sets its own secret and
# leaves DJANGO_DEBUG unset, which turns the debug pages off.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure--51d2o7b^ti-4c6rhsdae-ds901je-=b)70&!pdjnhim(ct^64')

DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# There is nothing user-specific behind this site — no login, no mail, no
# password reset — so the host header has nothing to poison.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # with DEBUG off Django stops serving static files itself; whitenoise hands
    # them straight out of the WSGI process, which is all a database-free site
    # needs — no bucket, no CDN, no second service
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # reads the /en/ prefix off the URL and activates that language
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'websitem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'portfolio.context_processors.language',
            ],
        },
    },
]

WSGI_APPLICATION = 'websitem.wsgi.application'


# No database: this site is a static CV/portfolio, content lives in portfolio/data.py


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

LANGUAGES = [
    ('tr', 'Türkçe'),
    ('en', 'English'),
]

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
